export const siteMeta = {
  legalName: "Impress Security Services Nigeria Limited",
  shortName: "Impress Security Services",
  tagline: "We Impress You With Our Services",
  promise: "We Secure Quietly. We Protect Effectively.",
  positioning: "Professional · Discreet · Intelligence-Driven",
  rc: "RC1821921",
  tin: "23977323-0001",
  nscdc: "NSCDC/PG/024/0001468",
  nscdcCategory: "Category B",
  incorporated: "27th July 2021",
  shareCapital: "10,000,000",
  chairman: "AIG Aderenle Shinaba (rtd), fdc, mni",
  chairmanRole: "Retired Assistant Inspector General of Police",
  licensingAuthority: "Hon. Dr. Olubunmi Tunji-Ojo, Minister/Licensing Authority",
  address: {
    line1: "Suite 19, Comfort Oladunni Shopping Complex",
    line2: "No. 3, Kosoko Road, Ojudu Berger",
    city: "Lagos",
    country: "Nigeria",
  },
  phones: ["0803 920 9495", "0816 6606 266"],
  email: "impresssecurities@gmail.com",
};
